name: Build LaTeX document
on:
  push:
    branches:
     - 'master'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            session-1.tex
            session-2.tex
            session-3.tex
            session-4.tex
            fpc-intro.tex
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          files: |
            session-1.pdf
            session-2.pdf
            session-3.pdf
            session-4.pdf
            fpc-intro.pdf
